### ISSUE TITLE
Feedback zum Testat

### ISSUE THREAD

**Issue by thomsmits** [tpe-lecture/repo-13#1]
Bitte korrigieren Sie die folgenden Fehler und checken Sie dann die korrigierte Version ein. Danach können Sie dieses Issue schließen.

  * JavaDoc ergänzen, diese fehlt vollständig
  * Entfernen Sie alle TODO-Kommentare

**Comment by kurnizki77** [comment]
JavaDoc jetzt dabei

**Comment by thomsmits** [comment]
Die JavaDoc ist nicht korrekt. `@param` dient dazu, Parameter zu kommentieren, nicht dazu, die Methode zu beschreiben. Bitte korrigieren Sie das.
