### ISSUE TITLE
Feedback zur Pflichtübung 2

### ISSUE THREAD

**Issue by thomsmits** [tpe-lecture/repo-13#2]
* ( -5) Preis in die Klasse Wesen ziehen, um das Design sauberer zu gestalten.
  * ( -5) Maximal zwei Anführer nicht geprüft
  * ( +0) Sonst alles sehr gut!
  
Live-Übung (+0): Keine Probleme 

**Summe: 90 Punkte**

**Comment by Pathen85** [comment]
Vielen Dank für das insgesamt positive Feedback! 
Jedoch gibt es Unklarheiten zu Ihrem zweiten Kritikpunkt, der beanstandet, dass in unserem Programm nicht überprüft wird, ob maximal zwei Anführer Teil eines Squads sind. Laut der Aufgabenstellung ist dies nämlich gar nicht gefordert: "In einem Squad können beliebig viele Wesen der jeweiligen Rasse vorhanden sein, der Anführer jeder Rasse aber nur einmal, also maximal vier Anführer." Ist es möglich, dass Sie noch eine frühere Aufgabenstellung im Kopf hatten, denn ich meine mich daran zu erinnern, dass kurz nach Ausgabe der Übung, die Aufgabe in diesem Punkt abgeändert wurde?

Mit freundlichen Grüßen 
Henrik Lawall

**Comment by thomsmits** [comment]
Sie haben Recht. Ich habe die Punkte korrigiert.

Summe: 95 Punkte
